### PR TITLE
add separate width options for overlay

### PR DESCRIPTION
**Pull request by Elypha**
Hello

thanks for the project! first time pr that a super simple enhancement which makes this option an inputint3 so that each col can have their separate width offset

the current master branch doesn't compile but hopefully it works x

### CODE REVIEW

**Comment by Limiana** [comment]
Hello! Thank you for the PR. You can not change type in JSON file from an int to array of ints, this will result in loading issues. What needs to be done is creation of new configuration field with new name and a migration code added upon config loading.
What's the issue with compiling? Did you try to update all submodules?

**Comment by Elypha** [comment]
thanks for the comment! it was a type error here https://github.com/Elypha/Lifestream/blob/pr-button-width/Lifestream/Utils.cs#L55 and seems I can fix it by adding a cast `if(IsKeyPressed((int)Keys.LButton))`

for the config migration may I know if you have any guidance like where to implement it for the sake of code consistancy? the plugin makes use of EzConfig which I'm not quite familiar with tho x

**Comment by Limiana** [comment]
Please check if your build configuration is configured like this, specifically with ECommons being set to "release with forms"
image
As for migration, just add a method to Utils and call it after configuration is loaded

**Comment by Elypha** [comment]
thanks for that! I was using the cli dotnet to build debug but in VS the release build worded fine so this seems to be the problem. should now be ready to merge and please give it a try!

**Comment by Limiana** [comment]
That looks nice for sure
Did you finished with PR now?

**Comment by Elypha** [comment]
so long as people find it useful x
yes it's ready for merge

**Comment by Elypha** [comment]
@Limiana hello just noticed that with the current implementation, the instance switch got some problems since it uses the same variable for width with housing wards.
if I'm not mistaken the overlay window seems to use `ResizeButton` method which in fact sets the base width to the widest button in the whole window which may subject to change and other offsets based on this may therefore visually broken due to this.
maybe it requires some kind of larger rework to update the current drawing logic to something like
a) collecting all members in a col
b) get the longest and set width once before draw
c) draw each member with that width

**Comment by Limiana** [comment]
I'll see what I can do about improving the UI

**Pull request merged**
